config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/create'
  get 'articles/new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/update'
  get 'articles/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end


  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="main-box">
  <h1>Editing article</h1>
  <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
  <div class="flex">
    <%= link_to "Show", article_path(@article) %>
    <%= link_to "Back", articles_index_path %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="main-box">
  <ul>
    <% @articles.each do |article|  %>
    <div class="article-margin">
      <li><%= link_to article.title, article_path(article) %></li>
      <p><%= article.content %></p>
    </div>
    <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<div class="main-box">
  <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
  <%= link_to "Back", articles_index_path %>
</div>

app/views/articles/show.html.erb
<div class="main-box">
  <div class="bottom-line">
    <h1><%= @article.title %></h1>
    <div>
      <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_article_path(@article) %>
      <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, article_path(@article), method: :delete, data: { confirm: "Are you sure?" }  %>
    </div>
  </div>
  <p><%= @article.content %></p>
</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flex">
      <%= link_to "Wikinimous", articles_index_path%>
      <%= link_to "New Article", articles_new_path%>
    </div>
    <%= yield %>
  </body>
</html>